sudo: false
group: stable
cache: bundler
addons:
  postgresql: '9.5'
  apt:
    packages:
      - graphviz
language: ruby
rvm:
  - '2.3.1'
before_script:
  - cp spec/dummy/config/database.yml.travis spec/dummy/config/database.yml
  - psql --version
  - bundle exec rake --version
  - bundle exec rake db:create db:migrate
script: bundle exec rake spec yard
